<?php

/**
 * @file
 * Contains alter_site_information.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function alter_site_information_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alter_site_information module.
    case 'help.page.alter_site_information':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Alter the site information, as well as provides the JSON representation of a given node with the content type "page"') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function alter_site_information_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'system_site_information_settings':
      $form['actions']['submit']['#value'] = t('Update Configuration');
      break;
  }
}
